name: 🚀 Feature request
description: Request a new feature or enhancement
title: "[FEATURE]: "
labels: ["feature", "feature_request"]

body:
- type: textarea
  attributes:
    label: Describe the feature request
    description: |
      Thank you for taking the time to file a feature request. Please provide a description of the feature you would like to see. Consider the following if relevant:
      - Motivation
      - Specific use case
      - Expected behavior
      - Work required to implement
      - Code examples or drawings
      
      Note that you can also send a pull request if you know how to implement the feature yourself. We are always looking for contributors and are happy to guide you through the process.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: |
      If you are willing to share, tell us a bit about your research use case for ROICaT.
  validations:
    required: false

- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!